# ############################################################################
# Model: RNN encoder-decoder with EnCodec audio representations (see https://arxiv.org/abs/2210.13438)
# Authors: Luca Della Libera 2023
# ############################################################################

# Adapted from:
# https://github.com/speechbrain/speechbrain/blob/unstable-v0.6/recipes/LibriSpeech/ASR/seq2seq/hparams/train_BPE_1000.yaml

experiment_name: !ref encodec

# Seed needs to be set at top of YAML
seed: 0
__set_seed: !apply:torch.manual_seed [!ref <seed>]

# Data preparation
data_folder: !PLACEHOLDER
train_csv: !ref <save_folder>/voicebank_trainset_28spk_wav.csv
valid_csv: !ref <save_folder>/voicebank_validset_wav.csv
test_csv: !ref <save_folder>/voicebank_testset_wav.csv
num_valid_speakers: 2

# Output folders
output_folder: !ref results/<experiment_name>/<seed>
save_folder: !ref <output_folder>/save

# Preprocessing parameters
train_remove_if_longer: 60.0  # Seconds
valid_remove_if_longer: 60.0  # Seconds
test_remove_if_longer: 60.0  # Seconds
sorting: ascending

# Training parameters
num_epochs: 100
grad_accumulation_factor: 1
dynamic_batching: False
train_batch_size: 1
valid_batch_size: 1
test_batch_size: 1
train_max_batch_length: 20.0  # Seconds
valid_max_batch_length: 20.0  # Seconds
test_max_batch_length: 20.0  # Seconds
num_buckets: 80
max_batch_size: 128
dataloader_workers: 4
nonfinite_patience: 10
max_grad_norm: 5.0
auto_mix_prec: True
ckpt_interval_minutes: 600
keep_checkpoints: 5
augment: False

# Special tokens
pad_index: 0  # NOTE: must be 0 to comply with SpeechBrain padding convention
bos_index: 1
eos_index: 2
token_shift: 3  # NOTE: must be equal to the number of defined special tokens

# Optimizer parameters
lr: 0.0001
weight_decay: 0.01
improvement_threshold: 0.0025
annealing_factor: 0.8
patient: 0
enable_scheduler: True

# Codec parameters
sample_rate: 24000  # NOTE: must match the codec's sample rate
vocab_size: !ref 1024 + <token_shift>  # NOTE: must match the codec's codebook size + the number of special tokens
bandwidth: 1.5  # The larger the bandwidth, the larger the sequence length

# Encoder/decoder parameters
embedding_dim: 256  # NOTE: must match the codec embedding size times the number of codebooks
dropout: 0.1
activation: !name:torch.nn.LeakyReLU
encoder_rnn_class: !name:speechbrain.nnet.RNN.LSTM
encoder_rnn_layers: 4
encoder_time_pooling_size: 4
encoder_rnn_bidirectional: True
encoder_rnn_neurons: 1024
encoder_dnn_blocks: 2
encoder_dnn_neurons: 512
decoder_rnn_type: lstm
decoder_rnn_layers: 1
decoder_neurons: 1024
decoder_attn_type: location
decoder_attn_dim: 1024
decoder_attn_channels: 10
decoder_attn_kernel_size: 100

# Search parameters
valid_search_freq: 1
beam_size: 4
min_decode_ratio: 0.0
max_decode_ratio: 1.0
temperature: 1.15

# Pretrained model (to load as initial checkpoint)
model_path: null

# Modules
# EnCodec model (see https://huggingface.co/docs/transformers/v4.31.0/en/model_doc/encodec) (applied during data loading on CPU)
codec: !new:speechbrain.lobes.models.huggingface_transformers.encodec.Encodec
    source: facebook/encodec_24khz  # Only the 24kHz version supports mono audio
    save_path: !ref <save_folder>
    sample_rate: !ref <sample_rate>
    bandwidth: !ref <bandwidth>
    flat_embeddings: True
    freeze: True
    renorm_embeddings: True

# Augmentation (applied during data loading on CPU)
augmentation: !new:speechbrain.lobes.augment.TimeDomainSpecAugment
    perturb_prob: 1.0
    drop_freq_prob: 0.0
    drop_chunk_prob: 0.0
    sample_rate: !ref <sample_rate>
    speeds: [95, 100, 105]

encoder_embedding: !new:torch.nn.Embedding
    num_embeddings: !ref <vocab_size>
    embedding_dim: !ref <embedding_dim>
    padding_idx: !ref <pad_index>

encoder: !new:speechbrain.lobes.models.CRDNN.CRDNN
    input_shape: [null, null, !ref <embedding_dim>]
    activation: !ref <activation>
    dropout: !ref <dropout>
    cnn_blocks: 0
    time_pooling: True
    using_2d_pooling: False
    time_pooling_size: !ref <encoder_time_pooling_size>
    rnn_class: !ref <encoder_rnn_class>
    rnn_layers: !ref <encoder_rnn_layers>
    rnn_neurons: !ref <encoder_rnn_neurons>
    rnn_bidirectional: !ref <encoder_rnn_bidirectional>
    dnn_blocks: !ref <encoder_dnn_blocks>
    dnn_neurons: !ref <encoder_dnn_neurons>
    rnn_re_init: True
    use_rnnp: False

decoder_embedding: !new:torch.nn.Embedding
    num_embeddings: !ref <vocab_size>
    embedding_dim: !ref <embedding_dim>
    padding_idx: !ref <pad_index>

decoder: !new:speechbrain.nnet.RNN.AttentionalRNNDecoder
    enc_dim: !ref <encoder_dnn_neurons>
    input_size: !ref <embedding_dim>
    rnn_type: !ref <decoder_rnn_type>
    hidden_size: !ref <decoder_neurons>
    dropout: !ref <dropout>
    num_layers: !ref <decoder_rnn_layers>
    attn_type: !ref <decoder_attn_type>
    attn_dim: !ref <decoder_attn_dim>
    channels: !ref <decoder_attn_channels>
    kernel_size: !ref <decoder_attn_kernel_size>
    re_init: True

ce_head: !new:speechbrain.nnet.linear.Linear
    input_size: !ref <decoder_neurons>
    n_neurons: !ref <vocab_size>

modules:
    #encoder_embedding: !ref <encoder_embedding>
    encoder: !ref <encoder>
    decoder_embedding: !ref <decoder_embedding>
    decoder: !ref <decoder>
    ce_head: !ref <ce_head>

model: !new:torch.nn.ModuleList
    [[#!ref <encoder_embedding>,
      !ref <encoder>,
      !ref <decoder_embedding>,
      !ref <decoder>,
      !ref <ce_head>]]

# Loss functions
ce_loss: !new:torch.nn.CrossEntropyLoss
    ignore_index: !ref <pad_index>

# Optimizers
opt_class: !name:torch.optim.AdamW
    lr: !ref <lr>
    betas: (0.9, 0.98)
    eps: 1.e-8
    weight_decay: !ref <weight_decay>

scheduler: !new:speechbrain.nnet.schedulers.NewBobScheduler
    initial_value: !ref <lr>
    improvement_threshold: !ref <improvement_threshold>
    annealing_factor: !ref <annealing_factor>
    patient: !ref <patient>

# Searchers
greedy_searcher: !new:speechbrain.decoders.S2SRNNBeamSearcher
    embedding: !ref <decoder_embedding>
    decoder: !ref <decoder>
    linear: !ref <ce_head>
    bos_index: !ref <bos_index>
    eos_index: !ref <eos_index>
    min_decode_ratio: !ref <min_decode_ratio>
    max_decode_ratio: !ref <max_decode_ratio>
    beam_size: 1

beam_searcher: !new:speechbrain.decoders.S2SRNNBeamSearcher
    embedding: !ref <decoder_embedding>
    decoder: !ref <decoder>
    linear: !ref <ce_head>
    bos_index: !ref <bos_index>
    eos_index: !ref <eos_index>
    min_decode_ratio: !ref <min_decode_ratio>
    max_decode_ratio: !ref <max_decode_ratio>
    beam_size: !ref <beam_size>
    temperature: !ref <temperature>

# Performance metrics
ter_computer: !name:speechbrain.utils.metric_stats.ErrorRateStats

# Counters, checkpointers, loggers, etc.
epoch_counter: !new:speechbrain.utils.epoch_loop.EpochCounter
    limit: !ref <num_epochs>

checkpointer: !new:speechbrain.utils.checkpoints.Checkpointer
    checkpoints_dir: !ref <save_folder>
    recoverables:
        model: !ref <model>
        scheduler: !ref <scheduler>
        counter: !ref <epoch_counter>

train_logger: !new:speechbrain.utils.train_logger.FileTrainLogger
    save_file: !ref <output_folder>/train_log.txt

# Pretrainer
pretrainer: !new:speechbrain.utils.parameter_transfer.Pretrainer
    collect_in: !ref <save_folder>
    loadables:
        model: !ref <model>
    paths:
        model: !ref <model_path>
    conditions:
        model: !ref <model_path>
