# ############################################################################
# Model: Autoregressive transformer with EnCodec audio representations (see https://arxiv.org/abs/2210.13438)
# Authors: Luca Della Libera 2023
# ############################################################################

experiment_name: dac_ar

# Seed needs to be set at top of YAML
seed: 0
__set_seed: !apply:torch.manual_seed [!ref <seed>]

# Data preparation
data_folder: !PLACEHOLDER
train_csv: !ref <save_folder>/librimix_<num_speakers>mix_train-100.csv
valid_csv: !ref <save_folder>/librimix_<num_speakers>mix_dev.csv
test_csv: !ref <save_folder>/librimix_<num_speakers>mix_test.csv
splits: [train-100, dev, test]
num_speakers: 2
add_noise: False
version: wav16k/min

# Output folders
output_folder: !ref results/<experiment_name>/<seed>
save_folder: !ref <output_folder>/save

# Save options
vocode: True
save_audios: True

# Preprocessing parameters
train_remove_if_longer: 60.0  # Seconds
valid_remove_if_longer: 60.0  # Seconds
test_remove_if_longer: 60.0  # Seconds
sorting: ascending

# Training parameters
num_epochs: 10
grad_accumulation_factor: 1
dynamic_batching: False
train_batch_size: 4
valid_batch_size: 4
test_batch_size: 4
train_max_batch_length: 40.0  # Seconds
valid_max_batch_length: 40.0  # Seconds
test_max_batch_length: 40.0  # Seconds
num_buckets: 40
max_batch_size: 128
dataloader_workers: 4
nonfinite_patience: 10
max_grad_norm: 0.001
precision: fp16
ckpt_interval_minutes: 600
keep_checkpoints: 2
augment: True
augment_prob: 0.75
snr: 5  # dB  # Used only if `add_noise` is True

# Optimizer parameters
lr: 0.0001
weight_decay: 0.01
improvement_threshold: 0.0025
annealing_factor: 0.9
patient: 0
enable_scheduler: True

# DAC parameters
# model_type: [16khz, 24khz, 44khz, 44khz]
# vocab_size: [1024, 1024, 1024, 1024]
# model_bitrate: [8kbps, 8kbps, 8kbps, 16kbps]
# max_num_codebooks: [12, 32, 9, 18]
# embedding_dim: [1024, 1024, 1024, 128]
sample_rate: 16000  # NOTE: must match DAC's model type
model_type: 16khz
vocab_size: 1024
model_bitrate: 8kbps
num_codebooks: 1  # NOTE: must be smaller or equal to the maximum number of codebooks for the given model type

# Special tokens
bos_index: !ref <vocab_size>
eos_index: !ref <vocab_size> + 1
pad_index: !ref <vocab_size> + 2

# Encoder parameters
embedding_dim: 128  # NOTE: if using pretrained embeddings, must match EnCodec's embedding size
dropout: 0.1
activation: !name:torch.nn.GELU
d_model: 256
nhead: 8
num_encoder_layers: 6
num_decoder_layers: 6
d_ffn: 2048
max_length: 5000
encoder_module: conformer
causal: False

# Search parameters
valid_search_freq: 1
beam_size: 1

# Augmentation
drop_freq: !new:speechbrain.augment.time_domain.DropFreq
    drop_freq_low: 0  # Min frequency band dropout probability
    drop_freq_high: 1  # Max frequency band dropout probability
    drop_freq_count_low: 1  # Min number of frequency bands to drop
    drop_freq_count_high: 3  # Max number of frequency bands to drop
    drop_freq_width: 0.05  # Width of frequency bands to drop

drop_chunk: !new:speechbrain.augment.time_domain.DropChunk
    drop_length_low: 1  # Min number of audio chunks to drop
    drop_length_high: 5  # Max number of audio chunks to drop
    drop_count_low: 1000  # Min length of audio chunks to drop
    drop_count_high: 2000  # Max length of audio chunks to drop

augmentation: !new:speechbrain.augment.augmenter.Augmenter
    parallel_augment: False
    concat_original: False
    repeat_augment: 1
    shuffle_augmentations: False
    min_augmentations: 2
    max_augmentations: 2
    augment_prob: !ref <augment_prob>
    augmentations: [!ref <drop_freq>, !ref <drop_chunk>]

# Modules
# DAC model (see https://github.com/descriptinc/descript-audio-codec)
codec: !new:dac.DAC
    model_type: !ref <model_type>
    model_bitrate: !ref <model_bitrate>
    load_pretrained: True
    tag: latest

embedding: !new:torch.nn.Embedding
    num_embeddings: !ref <vocab_size> + 3
    embedding_dim: !ref <embedding_dim>
    padding_idx: !ref <vocab_size> + 2

transformer: !new:speechbrain.lobes.models.transformer.TransformerASR.TransformerASR
    input_size: !ref <embedding_dim>
    tgt_vocab: !ref <vocab_size> + 3
    d_model: !ref <d_model>
    nhead: !ref <nhead>
    num_encoder_layers: !ref <num_encoder_layers>
    num_decoder_layers: !ref <num_decoder_layers>
    d_ffn: !ref <d_ffn>
    dropout: !ref <dropout>
    activation: !ref <activation>
    max_length: !ref <max_length>
    encoder_module: !ref <encoder_module>
    normalize_before: True
    causal: !ref <causal>

ce_head: !new:speechbrain.nnet.linear.Linear
    input_size: !ref <d_model>
    n_neurons: !ref <vocab_size> + 3

modules:
    embedding: !ref <embedding>
    transformer: !ref <transformer>
    ce_head: !ref <ce_head>

model: !new:torch.nn.ModuleList
    [[!ref <embedding>, !ref <transformer>, !ref <ce_head>]]

# Loss functions
ce_loss: !name:speechbrain.nnet.losses.nll_loss
    label_smoothing: 0.0
    allowed_len_diff: 0
    reduction: mean

# Optimizers
opt_class: !name:torch.optim.AdamW
    lr: !ref <lr>
    betas: (0.9, 0.98)
    eps: 1.e-8
    weight_decay: !ref <weight_decay>

# Schedulers
scheduler: !new:speechbrain.nnet.schedulers.NewBobScheduler
    initial_value: !ref <lr>
    improvement_threshold: !ref <improvement_threshold>
    annealing_factor: !ref <annealing_factor>
    patient: !ref <patient>

# Searchers
greedy_searcher: !new:speechbrain.decoders.S2STransformerGreedySearch
    modules: [!ref <transformer>, !ref <ce_head>]
    bos_index: !ref <bos_index>
    eos_index: !ref <eos_index>
    min_decode_ratio: 0.0
    max_decode_ratio: 1.0

beam_searcher: !new:speechbrain.decoders.S2STransformerBeamSearcher
    modules: [!ref <transformer>, !ref <ce_head>]
    bos_index: !ref <bos_index>
    eos_index: !ref <eos_index>
    min_decode_ratio: 0.0
    max_decode_ratio: 1.0
    beam_size: !ref <beam_size>

# Performance metrics
ter_computer: !name:speechbrain.utils.metric_stats.ErrorRateStats

# Counters, checkpointers, loggers, etc.
epoch_counter: !new:speechbrain.utils.epoch_loop.EpochCounter
    limit: !ref <num_epochs>

checkpointer: !new:speechbrain.utils.checkpoints.Checkpointer
    checkpoints_dir: !ref <save_folder>
    recoverables:
        model: !ref <model>
        scheduler: !ref <scheduler>
        counter: !ref <epoch_counter>

train_logger: !new:speechbrain.utils.train_logger.FileTrainLogger
    save_file: !ref <output_folder>/train_log.txt
